### PR TITLE
helpers/factory: default formatter valid exit code to 0

### LINKED ISSUE #216: Formatting: Show Error on failure
### Issues

- [X] I have checked [existing issues](https://github.com/nvimtools/none-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I understand that (deep in the weeds of) the documentation is describes that one can debug formatter failures as such:

```lua
            check_exit_code = function(code, stderr)
                local success = code <= 1
    
                if not success then
                    -- can be noisy for things that run often (e.g. diagnostics), but can
                    -- be useful for things that run on demand (e.g. formatting)
                    print(stderr)
                end
    
                return success
            end,
```

However, I think this should be the default. Moreover, I speculate that most people aren't bothered by this not being the default because it is just a minor inconvenience - *even though they'd indeed prefer it to be*.

For example, when editing a large HTML file using `none-ls`, prettier may just silently fail, my LSP will not be able to tell what's happening, and the only logical thing is to `:!prettier %` to debug the error.

I've updated my config here and it works fine, but it really is polluted (and there's an LSP timeout error):

```lua
local function check_formatter_exit_code(code, stderr)
    local success = code <= 0

    if not success then
        vim.schedule(function()
            logger:warn(('failed to run formatter: %s'):format(stderr))
        end)
    end

    return success
end

null_ls.setup({
        formatting.buf.with({
            check_exit_code = check_formatter_exit_code,
        }),
        formatting.cbfmt.with({
            check_exit_code = check_formatter_exit_code,
        }),
        formatting.cmake_format.with({
            check_exit_code = check_formatter_exit_code,
        }),
       ...
})
```

I think this is a sensible default choice but let me know if y'all think otherwise.

### Help

Yes

### Implementation help

Willing (and would prefer) to help.

### PR DESCRIPTION
**Pull request by barrett-ruth**
Resolves #216.

Warns on formatter failures, defaulting to `!= 0`.

Create a utility wrapper `helpers.check_exit_code` to maintain backwards compatibility. 

# TODO

1. `logger:warn` spawns a blocking notification (i.e. must press enter) and creates a timeout error if not pressed within the defualt timeout

^ this is unavoidable - addressed by using a shorter initial message pointing you to to the log file.

### CODE REVIEW

**Comment by barrett-ruth** [comment]
@mochaaP I can't assign reviewers so please take a look. I know I need to squash commits and a bunch of other stuff but I just wanted to draft the initial API. Let me know everything that can be improved.

**Comment by barrett-ruth** [comment]
@mochaaP I'm going to start going through the formatters one-by-one (pain) to ensure I'm passing the right exit code. 

1. Is there a better way to do this?
2. I currently make it optional (and default to exit code 0) to indicate formatter success in `check_exit_code`. Is this fine?

**Comment by mochaaP** [comment]
I think (2) is fine.

For (1), we could land the changes first and wait for feedback from ones who actually use them if any problem arises.

**Comment by barrett-ruth** [comment]
Ready for review.

File: lua/null-ls/helpers/formatter_factory.lua [hunk 1]
```diff
@@ -18,5 +18,10 @@ return function(opts)
         return done({ { text = output } })
     end
 
+    if opts.check_exit_code == nil then
+        vim.print(opts)
```
Comment (mochaaP) [inline lua/null-ls/helpers/formatter_factory.lua:22]: Forgot to clean up a debug print?

File: lua/null-ls/helpers/check_exit_code.lua [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+        end
+
+        if not success then
+            vim.schedule(function()
+                logger:warn(string.format("failed to run formatter %s; see `:NullLsLog`", command))
+                logger:add_entry(string.format("failed to run formatter %s: %s", command, stderr), "warn")
+            end)
+        end
+    end
+end
```
Comment (mochaaP) [inline lua/null-ls/helpers/check_exit_code.lua:20]: duplicated here:

https://github.com/nvimtools/none-ls.nvim/blob/main/lua%2Fnull-ls%2Fhelpers%2Fgenerator_factory.lua#L135-L140

File: lua/null-ls/helpers/formatter_factory.lua [hunk 3]
```diff
@@ -18,5 +18,10 @@ return function(opts)
         return done({ { text = output } })
     end
 
+    if opts.check_exit_code == nil then
```
Comment (mochaaP) [inline lua/null-ls/helpers/formatter_factory.lua:21]: Set `check_exit_code` in the generator factory instead of here.

**Review by mochaaP — CHANGES_REQUESTED** [review]

**Comment by barrett-ruth** [comment]
@mochaaP addressing comments above but this is a longer response:

The problem I have with moving the code to the generic factory (and this includes the code duplication comment above) is that I thought this feature only makes sense for formatters.

If we added this to generator factory, wouldn't we also be checking linting exit codes as well?

**Comment by barrett-ruth** [comment]
@mochaaP this is ready for review, see above comments

**Comment by barrett-ruth** [comment]
What does the eyes emoji mean :sob: I've already addressed the comments I thought... what do you think? (lol)

**Comment by mochaaP** [comment]
“I will take a look at it” 😂 This needs some slight changes, I will take care of it.

**Comment by mochaaP** [comment]
Do you think this implementation is okay?

**Comment by barrett-ruth** [comment]
I see. You just set the exit code to `0` in the code and then that's picked up later in the parsing.

Much cleaner implementation, LGTM.

**Comment by barrett-ruth** [comment]
@mochaaP you updated the logging message to use `logger:add_entry`.

Then you deleted the file containing that change (`check_exit_code`) - lol! I'm wondering if this was intentional? I thought we wanted this informative message to the end user?

If this is the case, I thought we had to separate the logic out in another file to do that log... because *only* in the formatters does the notion of validating the exit code make sense.

Sorry this is taking so long, LMK if you know what I'm saying.

**Comment by mochaaP** [comment]
ack, will check tonight.

**Comment by barrett-ruth** [comment]
LGTM!

**Comment by geril2207** [comment]
@mochaaP @barrett-ruth 
prettierd nvim(nightly but idk if it changes anything):

https://github.com/user-attachments/assets/32938e71-b5d5-430f-ba95-b89c35eaacea

before:

https://github.com/user-attachments/assets/ccdb13ba-d102-472c-a25f-19be9b010b9e

**Comment by mochaaP** [comment]
cc @barrett-ruth is prettierd outputting to stdout? we might need to ignore that

**Comment by daephx** [comment]
Found myself here because I updated none-ls and keep getting the error `nvim_echo must not be called in a lua loop callback` when the buffer has invalid syntax. I've only tested with `stylua`, and haven't checked other formatters.

The error output itself is rather annoying, so for now my solution is to pin none-ls to commit 83c7c00.

**Comment by mochaaP** [comment]
I've partially reverted this until I figure out a better way to present the error message.
